backend:
  name: git-gateway
  branch: main
media_folder: public/img #images that are uploaded via Netlify Cms interface will be stored in this folder
public_folder: img #I dont know
publish_mode: editorial_workflow
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Posts" # Used in the UI
    label_singular: "Post"
    summary: "{{year}}-{{month}}-{{day}}"
    folder: "_posts" # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: "{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - label: "Date"
        name: "date"
        widget: "datetime"
        comment: 'Date the post will be published (only one post per day)'
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Excerpt"
        name: "excerpt"
        widget: "string"
        required: false
        comment: 'Post description is automatically generated by headings in the body, this overwrites that display'
      - label: "Body"
        name: "body"
        widget: "markdown"